In [1]:
import cv2 
import numpy as np

In [52]:
qrcode = [[ 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1 ],
          [ 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1 ],
          [ 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1 ],
          [ 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1 ],
          [ 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1 ],
          [ 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1 ],
          [ 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1 ],
          [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
          [ 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1 ],
          [ 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1 ],
          [ 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1 ],
          [ 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0 ],
          [ 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0 ],
          [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0 ],
          [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1 ],
          [ 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0 ],
          [ 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1 ],
          [ 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0 ],
          [ 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1 ],
          [ 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0 ],
          [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1 ]]

In [66]:
import qrcode
# example data
data = "Ллллл"
# output file name
filename = "site.png"
# generate qr code
img = qrcode.make(data)
# save img to a file
img.save(filename)

In [67]:
img = cv2.imread("site.png")

In [68]:
img.shape

(290, 290, 3)

In [69]:
detector = cv2.QRCodeDetector()

In [70]:
data, bbox, straight_qrcode = detector.detectAndDecode(img)

In [71]:
data

'Ллллл'

In [72]:
bbox

array([[[ 40.,  40.]],

       [[249.,  40.]],

       [[249., 249.]],

       [[ 40., 249.]]], dtype=float32)

In [73]:
if bbox is not None:
    print(f"QRCode data:\n{data}")
    # display the image with lines
    # length of bounding box
    n_lines = len(bbox)
    for i in range(n_lines):
        # draw all lines
        point1 = tuple(bbox[i][0])
        point2 = tuple(bbox[(i+1) % n_lines][0])
        cv2.line(img, point1, point2, color=(255, 0, 0), thickness=2)

QRCode data:
Ллллл


In [74]:
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
arr = []
bit_seq = []
for i in range (21):
    bit_seq = []
    for j in range (21):
        if (i + j) % 2 == 0:
            element = int (not qrcode[i][j])
        else:
            element = qrcode[i][j]
        
        bit_seq.append(element)
    
    arr.append(bit_seq)

In [4]:
arr = np.array(arr)
arr

array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,

In [5]:
right_part = np.array([[0, 1, 1, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0]])

In [47]:
right_part = arr[-12 : , -8 : ]

In [48]:
right_part

array([[0, 1, 1, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0]])

In [6]:
left_part = np.vstack( (arr[0 : 6, 9 : 13], arr[7 : , 9 : 13]) ) 

In [7]:
left_part.shape

(20, 4)

In [8]:
left_part

array([[1, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 1, 0]])

In [9]:
last_part = np.hstack( (arr[9 : 13, 0 : 6], arr[9 : 13, 7 : 9 ]) )
last_part

array([[0, 0, 0, 1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0]])

In [10]:
right_part

array([[0, 1, 1, 0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 1, 0]])

In [11]:
def extract_up(arr):
    bit_seq = ''
    for i in range (arr.shape[0] - 1, -1, -1):
        bit_seq += str (arr[i, 1])
        bit_seq += str (arr[i, 0])
    return bit_seq

In [12]:
def extract_down(arr):
    bit_seq = ''
    for i in range (0, arr.shape[0], 1):
        bit_seq += str (arr[i, 1])
        bit_seq += str (arr[i, 0])
    return bit_seq

In [13]:
def extract_hor(arr):
    bit_seq = ''
    left = arr[: , :2]
    right = arr[: , 2:4]
    bit_seq += extract_up(right)
    bit_seq += extract_down(left)
    return bit_seq

In [14]:
def extract_hor_inv(arr):
    bit_seq = ''
    left = arr[: , :2]
    right = arr[: , 2:4]
    bit_seq += extract_down(right)
    bit_seq += extract_up(left)
    return bit_seq

In [92]:
right_part

array([[1, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 0]])

In [91]:
right_part [6 : 10, -2 :]

array([[1, 1],
       [1, 0],
       [0, 0],
       [0, 0]])

In [29]:
right_part [ : 2,  : 4]

array([[0, 1, 1, 0],
       [1, 1, 0, 0]])

In [83]:
def text_from_bits(bits, encoding='utf-8', errors='surrogatepass'):
    n = int(bits, 2)
    return n.to_bytes((n.bit_length() + 7) // 8, 'big').decode(encoding, errors)

In [88]:
qrcode = [  [ 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1 ],
                                      [ 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1 ],
                                      [ 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1 ],
                                      [ 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1 ],
                                      [ 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1 ],
                                      [ 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1 ],
                                      [ 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1 ],
                                      [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],
                                      [ 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1 ],
                                      [ 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1 ],
                                      [ 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1 ],
                                      [ 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1 ],
                                      [ 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1 ],
                                      [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0 ],
                                      [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1 ],
                                      [ 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1 ],
                                      [ 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1 ],
                                      [ 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0 ],
                                      [ 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1 ],
                                      [ 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0 ],
                                      [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1 ]]

In [95]:

    import numpy as np

    def extract_up(arr):
        bit_seq = ''
        for i in range (arr.shape[0] - 1, -1, -1):
            bit_seq += str (arr[i, 1])
            bit_seq += str (arr[i, 0])
        return bit_seq

    def extract_down(arr):
        bit_seq = ''
        for i in range (0, arr.shape[0], 1):
            bit_seq += str (arr[i, 1])
            bit_seq += str (arr[i, 0])
        return bit_seq

    def extract_hor(arr):
        bit_seq = ''
        left = arr[: , :2]
        right = arr[: , 2:4]
        bit_seq += extract_up(right)
        bit_seq += extract_down(left)
        return bit_seq

    def extract_hor_inv(arr):
        bit_seq = ''
        left = arr[: , :2]
        right = arr[: , 2:4]
        bit_seq += extract_down(right)
        bit_seq += extract_up(left)
        return bit_seq

    def text_from_bits(bits, encoding='utf-8', errors='surrogatepass'):
        n = int(bits, 2)
        return n.to_bytes((n.bit_length() + 7) // 8, 'big').decode(encoding, errors)

    def decode (right_part):
        letters = ''
        counter = 0
        seq_length = int( extract_up(right_part [6 : 10, -2 :]), 2)


        first_letter = extract_up (right_part [2 : 6, -2 : ])
        try:
            first_letter = text_from_bits (first_letter)
            letters += first_letter
            counter += 1
        except:
            return letters[: -1]

        second_letter = extract_hor (right_part [ : 2, -4 : ])
        try:
            second_letter = text_from_bits (second_letter)
            letters += second_letter
            counter += 1
        except:
            return letters[:-1]

        third_letter = extract_down (right_part [2 : 6, -4 : -2])
        try:
            third_letter = text_from_bits (third_letter)
            letters += third_letter
            counter += 1
        except:
            return letters[:-1]

        fourth_letter = extract_down(right_part [-6 :-2, 4 : 6])
        try:
            fourth_letter = text_from_bits (fourth_letter)
            letters += fourth_letter
            counter += 1
        except:
            return letters[:-1]

        fifth_letter = extract_hor_inv (right_part [ -2 : , 2 : 6])
        try:
            fifth_letter = text_from_bits (fifth_letter)
            letters += fifth_letter
            counter += 1
        except:
            return letters[:-1]

        sixth_letter = extract_up (right_part [-6 : -2, 2 : 4])
        try:
            sixth_letter = text_from_bits(sixth_letter)
            letters += sixth_letter
            counter += 1
        except:
            return letters[:-1]

        seventh_letter = extract_up (right_part [2 : 6, 2 : 4])
        try:
            seventh_letter = text_from_bits(seventh_letter)
            letters += seventh_letter
            counter += 1
        except:
            return letters[:-1]

        try:
            if counter == seq_length:
                return letters
            else: 
                eighth_letter = extract_hor (right_part [ : 2,  : 4])
                eighth_letter = text_from_bits(eighth_letter)
                letters += eighth_letter
                return letters
        except:
            return letters[:-1]

    arr = []
    bit_seq = []
    for i in range (21):
        bit_seq = []
        for j in range (21):
            if (i + j) % 2 == 0:
                element = int (not qrcode[i][j])
            else:
                element = qrcode[i][j]

            bit_seq.append(element)

        arr.append(bit_seq)

    arr = np.array(arr)    
    right_part = arr[-12 : , -8 : ]

    decode(right_part)

'Warrior'

In [20]:
arr

array([[0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,

In [96]:
def scanner(qrc):
    bits = ''.join( str(qrc[x][y] ^ ((x+y)%2==0)) for x,y in ticTocGen())
    size = int(bits[4:12],2)
    return ''.join( chr(int(bits[i:i+8],2)) for i in range(12,12+8*size,8))


def ticTocGen():
    x,y,dx = 20,20,-1
    while y>13: 
        yield from ( (x,y-dy) for dy in range(2) )
        x+=dx
        if x==8 or x>20:
            dx *= -1
            y  -= 2
            x   = x==8 and 9 or 20

In [97]:
scanner(qrcode)

'Warrior'